### ISSUE TITLE
iOS Wallet Connect Authorize Transaction Prompt Instantly Closing

### ISSUE THREAD

**Issue by barnjamin** [perawallet/pera-wallet#36]
While testing an application that uses wallet connect several iOS users reported issues around the signing prompt.

4 - Authorize Prompt would open and instantly close
2 - Authorize Prompt would be approved and nothing made it back to the web application
3 - Worked the first time without restarting the app

In all cases restarting the mobile app seemed to fix the issue. These were all using the TestNet network setting.

Since restarting the mobile app allowed the transaction to be authorized I suspect there is some cached field or setting causing this behavior but I'm not sure where to look.

**Comment by Im0** [comment]
I've had these problems a number of times utilising wallet connect and figured I might have to run my own bridge connect to make it stable.  Thanks @barnjamin for giving me the insight that perhaps it occurs when swapping from main->testnet.

Reproduction steps:
1. Logged into AlgorandWallet (main net)
2. Swapped to Test Net
3. Went to my site using Wallet Connect
4. Scanned QR code
5. Spinner came up in the wallet waiting for the connection prompt.  Nothing came up and after a minute I was taken back to the accounts page.
6. Closed the application and logged back in (iOS).  Re-scanned the QR code... spinner came up.  Same thing happened again.

The fix was:
1. Close the wallet iOS app
2. Refresh the webpage/QR code

If it breaks the first time, it looks like you need to refresh the QR code along with restarting the iOS app.

ps. It may also be worth whilst considering how long the timeout is before punting users back to the accounts screen.  It _feels_ too long.

**Comment by taylanpince** [comment]
I believe that with the fixes we pushed in February and March we've resolved these WalletConnect issues.
