### ISSUE TITLE
If Connected prompt is ignored, cannot sign first tx

### ISSUE THREAD

**Issue by every-time** [perawallet/pera-wallet#77]
Steps to reproduce:

1. Connect to a website.
2. Ignore the "You are Connected to ..." prompt.
3. Trigger a transaction on the website.
4. The "Unsigned Transactions" prompt will be behind the Connected prompt. Upon clicking "Close" on the Connected prompt, both the "Unsigned Transactions" and Connected prompts disappear.

**Comment by Sau1707** [comment]
Same problem,
[here ](https://drive.google.com/file/d/1ITdnpzafSi4vEEYbNakxwSRgWUIrj335/view) there is the video of the bug.

The transaction that I send after 5 seconds get closed by closing the button of the "You are Connected to ..."

**Comment by taylanpince** [comment]
Thank you for this, we are investigating the issue.

**Comment by rubendg** [comment]
I can confirm this happens on Android, pera wallet v5.3.0. 

I'm using https://www.npmjs.com/package/@walletconnect/client and the dismissal of the popup causes the dapp to hang until the transaction is either confirmed or cancelled, any subsequent retries throw the following error `Error: Transaction Request Rejected: The User currently has another transaction request that is in progress.`. The only way to recover from this is to disconnect and establish a new session.

**Comment by rubendg** [comment]
I can confirm this happens on Android, pera wallet v5.3.0.

I'm using https://www.npmjs.com/package/@walletconnect/client and the dismissal of the popup causes the dapp to hang until the transaction is either confirmed or cancelled, any subsequent retries throw the following error Error: Transaction Request Rejected: The User currently has another transaction request that is in progress..

In order to (partially) recover, I close and re-open pera, re-issue the transaction, the transaction succeeds, but the subsequent transaction fails again, and I have to repeat the same process.

**Comment by yigitguler** [comment]
Tracking this internally.

**Comment by yigitguler** [comment]
This seems to be resolved according to our tests. Please let me know if you still experience this problem.
